Allow null value for $userId
yiisoft/access pull request #13
Opened 2022-01-08 10:10 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | -

2022-01-08 16:08 UTC, vjik requested changes
Need changelog with @roxblnfk (https://github.com/yiisoft/access/pull/9)

2022-01-08 16:08 UTC, vjik commented on src/AccessCheckerInterface.php
> +     * @param int|string|null $userId the user ID representing the unique identifier of a user. If ID is null, it means user is a guest.
```suggestion
     * @param int|string|null $userId The user ID representing the unique identifier of a user.
     * If ID is null, it means user is a guest.
```

2022-01-08 21:19 UTC, samdark approved these changes

2022-01-08 21:20 UTC, samdark commented
Looks 👍 I think we can release it as a patch version. Would you please add a line for CHANGELOG?

2022-01-09 06:17 UTC, vjik commented on CHANGELOG.md
> +- Chg #13: Allowed passing a null value in $userId to check the permission of the guest user (@rustamwin)
```suggestion
- Chg #9: Type of `$userId` in the method `AccessCheckerInterface::userHasPermission()` is specified (@roxblnfk)
- Chg #13: Allowed passing a null value in `$userId` to check the permission of the guest user (@rustamwin)
```

2022-01-09 07:08 UTC, vjik approved these changes

2022-01-10 09:27 UTC, merged